### ISSUE TITLE
Sebastian Config for Templates

### ISSUE THREAD

**Issue by MattR-Joyent** [andrewh1978/sup#1]
Testing spec mentions that the config needs altering for Sebastian, but there is no direction for where the config file resides, so from the KB doc: 

_For now, in order to make sebastian work with these templates, the config file must be edited. This config file is "/opt/local/lib/node_modules/sebastian/etc/config.js", and the value you're looking for is "templates_directory". This is currently set to "/opt/local/lib/triton-cloud-notification-templates/new_notification_templates"._

**Comment by andrewh1978** [comment]
I think this is obsolete. Closing.
