### ISSUE TITLE
Moved To Sup-Notify

### ISSUE THREAD

**Issue by qdzlug** [andrewh1978/sup#2]
Hi,

I just checked this into /sup-notify/deployment in order to keep it all in the same place and to make it easier to doc.

jay

**Comment by travispaul** [comment]
@qdzlug looks like that change was reverted? Is the plan to keep it here? Just want to make sure I make any pull requests to the right location.

Thanks!

**Comment by qdzlug** [comment]
Yeah, we can probably close this out - I'm not sure what I was thinking here.....
